name: Render and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

## If you need to clear the cache, update the number inside cache-version as
## discussed at https://github.com/r-lib/actions/issues/86.
## Note that you can always run a GHA test without the cache by using the word
## "/nocache" in the commit message.
env:
  cache-version: 'cache-v1'

jobs:
  render:
    runs-on: macOS-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.1'
          crayon.enabled: 'FALSE'

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Set up TinyTex
        uses: r-lib/actions/setup-tinytex@v1

      - name: Install X11 dependencies on MacOS
        if: runner.os == 'macOS'
        run: |
          brew install --cask xquartz

      - name: Cache Renv packages
        if: "!contains(github.event.head_commit.message, '/nocache')"
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          key: ${{ env.cache-version }}-renv-${{ hashFiles('renv.lock') }}
          restore-keys: ${{ env.cache-version }}-renv-

      - name: Install packages
        run: |
          R -e 'install.packages("renv")'
          R -e 'renv::restore()'

      - name: Session info
        run: |
          install.packages('sessioninfo')
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Cache knitr results
        if: "!contains(github.event.head_commit.message, '/nocache')"
        uses: actions/cache@v2
        with:
          path: '**/*_cache'
          key: ${{ env.cache-version }}-knitr-${{ runner.os }}
          restore-keys: ${{ env.cache-version }}-knitr-

      - name: Render site
        run: |
          rmarkdown::render_site()
        shell: Rscript {0}

      - name: Deploy 🚀
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: _site

      - name: Upload LaTeX logs
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: latex-logs
          path: |
            *.log
            *.tex
